# Generated by Django 5.1.4 on 2024-12-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_text_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='created_at',
        ),
    ]
